freebsd_instance:
  image_family: freebsd-12-1

task:
  install_script:
    pkg install -y ccache e2fsprogs-libuuid postgresql12-server
    postgresql12-client postgresql-libpgeasy valgrind-devel fcgi-devkit
  script: ./configure ; make check

