os: linux
dist: bionic


language: c

compiler:
  - gcc

before_install:
  - sudo apt update
  - sudo apt install uuid-dev
  - sudo apt install valgrind
  - pip install --user cpp-coveralls

script:
  -  ./configure --enable-gcov make check

after_success:
  - coveralls --gcov-options '\lp'

