os: linux
dist: bionic


language: c

compiler:
  - musl-gcc

before_install:
  - sudo apt update
  - sudo apt install libgc-dev
  - sudo apt install musl-dev
  - sudo apt install musl-tools

script:
  - make test

