os: linux
dist: bionic


language: c

compiler:
  - gcc

before_install:
  - sudo apt update
  - sudo apt install uuid-dev
  - sudo apt install valgrind
  - sudo apt install gcovr

script:
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash)

