os: linux
dist: bionic


language: c

compiler:
  - gcc

before_install:
  - sudo apt update
  - sudo apt install uuid-dev
  - sudo apt install valgrind
  - sudo apt install libfcgi-dev
  - pip install --user cpp-coveralls

script:
  -  make check

after_success:
  - coveralls --gcov-options '\lp'

